<?php

namespace Admin\CategoryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
use Doctrine\ORM\Query;
use Closure;
use Admin\CommonBundle\Entity\Common;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{
    public function getList($amExtraParameters = array())
    {
        $query = $this->createQueryBuilder('C')
                    ->orderBy('C.root, C.lft', 'ASC');

        return Common::setCriteria($query, 'C', $amExtraParameters);
    }

    public function getIndentedTitle() {
        return str_repeat("--", $this->lvl).$this->title;
    }
}
