<?php

namespace Admin\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Admin\CommonBundle\Entity\Common;
use Symfony\Component\HttpFoundation\Session;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getList($amExtraParameters = array())
    {
        $query = $this->createQueryBuilder('U');
        return Common::setCriteria($query, 'U', $amExtraParameters);
    }
}
